services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    networks:
      - listmonk
    environment:
      - POSTGRES_DB=${LISTMONK_db__database}
      - POSTGRES_USER=${LISTMONK_db__user}
      - POSTGRES_PASSWORD=${LISTMONK_db__password}
    restart: unless-stopped
    volumes:
      - type: volume
        source: listmonk-db
        target: /var/lib/postgresql/data

  frontend:
    build:
      context: ../
      dockerfile: rtm/dev.Dockerfile
      args:
        - USER=${USER}
        - UID=${UID}
        - GID=${GID}
    user: "${UID}:${GID}"
    command: ["make", ".rtm-dev-frontend"]
    ports:
      - "9000:9000"
    environment:
      - LISTMONK_API_URL=http://${LISTMONK_app__address}
      - LISTMONK_FRONTEND_HOST=frontend
      - LISTMONK_FRONTEND_PORT=9000
    depends_on:
      - backend
    volumes:
      - ../:/app
    networks:
      - listmonk

  backend:
    build:
      context: ../
      dockerfile: rtm/dev.Dockerfile
      args:
        - USER=${USER}
        - UID=${UID}
        - GID=${GID}
    user: "${UID}:${GID}"
    command: ["make", ".rtm-dev-backend"]
    ports:
      - "9000"
    environment:
      - LISTMONK_ADMIN_USER=${LISTMONK_ADMIN_USER}
      - LISTMONK_ADMIN_PASSWORD=${LISTMONK_ADMIN_PASSWORD}
      - LISTMONK_app__address=${LISTMONK_app__address}
      - LISTMONK_db__host=${LISTMONK_db__host}
      - LISTMONK_db__port=${LISTMONK_db__port}
      - LISTMONK_db__database=${LISTMONK_db__database}
      - LISTMONK_db__user=${LISTMONK_db__user}
      - LISTMONK_db__password=${LISTMONK_db__password}
      - LISTMONK_db__ssl_mode=${LISTMONK_db__ssl_mode}
      - LISTMONK_db__max_open=${LISTMONK_db__max_open}
      - LISTMONK_db__max_idle=${LISTMONK_db__max_idle}
      - LISTMONK_db__max_timespan="${LISTMONK_db__max_timespan}
    depends_on:
      - db
    volumes:
      - ../:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    networks:
      - listmonk

volumes:
  listmonk-db:

networks:
  listmonk: