services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    networks:
      - listmonk
    environment:
      - POSTGRES_DB=${LISTMONK_db__database}
      - POSTGRES_USER=${LISTMONK_db__user}
      - POSTGRES_PASSWORD=${LISTMONK_db__password}
    restart: unless-stopped
    volumes:
      - type: volume
        source: listmonk-db
        target: /var/lib/postgresql/data

  frontend:
    image: listmonk--rtm_dev:latest
    restart: always
    command: ["make", ".rtm-dev-frontend"]
    ports:
      - "9000:9000"
    environment:
      - LISTMONK_API_URL=http://${LISTMONK_app__address}
      - LISTMONK_FRONTEND_HOST=frontend
      - LISTMONK_FRONTEND_PORT=9000
    depends_on:
      - backend
    volumes:
      - .:/app
    networks:
      - listmonk

  backend:
    image: listmonk--rtm_dev:latest
    command: ["make", ".rtm-dev-backend"]
    ports:
      - "9000"
    env_file: "dev.env"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - listmonk

volumes:
  listmonk-db:

networks:
  listmonk: