services:
  mailpit:
    image: axllent/mailpit:v1.20
    volumes:
      - listmonk-mailpit:/data
    networks:
      - listmonk
    restart: unless-stopped
    ports:
      - "1025"
      - "8025:8025"
    environment:
      - MP_MAX_MESSAGES=5000
      - MP_DATABASE=/data/mailpit.db
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    networks:
      - listmonk
    environment:
      - POSTGRES_DB=${LISTMONK_db__database}
      - POSTGRES_USER=${LISTMONK_db__user}
      - POSTGRES_PASSWORD=${LISTMONK_db__password}
    restart: unless-stopped
    volumes:
      - listmonk-db:/var/lib/postgresql/data

  frontend:
    image: listmonk--rtm_dev:latest
    restart: always
    command: ["make", ".rtm-dev-frontend"]
    ports:
      - "9000:9000"
    environment:
      - LISTMONK_API_URL=http://${LISTMONK_app__address}
      - LISTMONK_FRONTEND_HOST=frontend
      - LISTMONK_FRONTEND_PORT=9000
    depends_on:
      - backend
    volumes:
      - .:/app
    networks:
      - listmonk

  backend:
    image: listmonk--rtm_dev:latest
    command: ["make", ".rtm-dev-backend"]
    ports:
      - "9000"
    env_file: "rtm/dev.env"
    depends_on:
      - db
      - mailpit
    volumes:
      - .:/app
      - listmonk-go-pkgs:/go/pkg/mod/cache
    networks:
      - listmonk

volumes:
  listmonk-db:
  listmonk-mailpit:
  listmonk-go-pkgs:

networks:
  listmonk: